stages:
  - test

variables:
  PYTHON_VERSION: "3.10"

before_script:
  - apt-get update -qy
  - apt-get install -y python${PYTHON_VERSION} python${PYTHON_VERSION}-venv

test:
  stage: test
  script:
    - python${PYTHON_VERSION} -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt  # Install your project dependencies
    - python${PYTHON_VERSION} -m unittest discover -s test -p 'test_*.py'
