stages:
  - test
  - cleanup

test:
  stage: test
  image: python:3.10
  script:
    - /usr/local/bin/python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
    - python -m unittest discover -s test -p 'test_*.py'

cleanup:
  stage: cleanup
  script:
    - echo "Cleaning up runner cache"
    - gitlab-runner verify --delete-cache
