stages:
  - test

test:
  stage: test
  image: python:3.8
  script:
    - /usr/local/bin/python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - /usr/local/bin/python -m unittest discover -s test -p 'test_*.py'